spring:
  application:
    name: flowpay

  datasource:
    url: jdbc:postgresql://localhost:5432/flowpay_db
    username: postgres
    password: bush123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

flowpay:
  webhook:
    secret: flowpay-webhook-secret